/*
 * apply_lease.c — install a bound DHCPv4 lease.
 *
 * Three sub-steps, each independently fallible:
 *   1. SIOCAIFADDR to add the lease's address + netmask + derived
 *      broadcast to the interface (this is the FreeBSD-native
 *      "add an alias" path; the kernel also auto-installs the
 *      connected /N route to the LAN).
 *   2. PF_ROUTE RTM_ADD for the default route via lease->router.
 *   3. Write nameserver lines to /etc/resolv.conf (best-effort;
 *      no fsync, no atomic-rename — iter 4 replaces this with a
 *      proper SCDynamicStore publish).
 */
#include "apply_lease.h"

#include <sys/types.h>
#include <sys/ioctl.h>
#include <sys/socket.h>

#include <net/if.h>
#include <net/route.h>
#include <netinet/in.h>
#include <netinet/in_var.h>

#include <arpa/inet.h>

#include <errno.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static void
xlog(const char *fmt, ...)
{
	va_list ap;

	(void)fprintf(stderr, "ipconfigd[apply] ");
	va_start(ap, fmt);
	(void)vfprintf(stderr, fmt, ap);
	va_end(ap);
	(void)fputc('\n', stderr);
	(void)fflush(stderr);
}

static int
apply_address(const char *ifname, const struct dhcp_lease *lease)
{
	struct in_aliasreq req;
	int sock, rc;

	(void)memset(&req, 0, sizeof(req));
	(void)strlcpy(req.ifra_name, ifname, sizeof(req.ifra_name));

	req.ifra_addr.sin_family = AF_INET;
	req.ifra_addr.sin_len = sizeof(struct sockaddr_in);
	req.ifra_addr.sin_addr = lease->addr;

	req.ifra_mask.sin_family = AF_INET;
	req.ifra_mask.sin_len = sizeof(struct sockaddr_in);
	req.ifra_mask.sin_addr = lease->netmask;

	req.ifra_broadaddr.sin_family = AF_INET;
	req.ifra_broadaddr.sin_len = sizeof(struct sockaddr_in);
	/* Broadcast = (addr & netmask) | ~netmask. */
	req.ifra_broadaddr.sin_addr.s_addr =
	    (lease->addr.s_addr & lease->netmask.s_addr) |
	    ~lease->netmask.s_addr;

	sock = socket(AF_INET, SOCK_DGRAM, 0);
	if (sock < 0) {
		xlog("socket(AF_INET) failed: %s", strerror(errno));
		return (-1);
	}
	rc = ioctl(sock, SIOCAIFADDR, &req);
	if (rc != 0)
		xlog("SIOCAIFADDR(%s) failed: %s", ifname,
		    strerror(errno));
	(void)close(sock);
	return (rc);
}

/*
 * Add a default route to lease->router via the PF_ROUTE socket.
 * Mirrors what `route add default <router>` does.
 */
static int
install_default_route(const struct dhcp_lease *lease)
{
	struct {
		struct rt_msghdr	hdr;
		struct sockaddr_in	dst;
		struct sockaddr_in	gw;
		struct sockaddr_in	mask;
	} msg;
	int sock;
	ssize_t n;

	(void)memset(&msg, 0, sizeof(msg));
	msg.hdr.rtm_msglen = sizeof(msg);
	msg.hdr.rtm_version = RTM_VERSION;
	msg.hdr.rtm_type = RTM_ADD;
	msg.hdr.rtm_addrs = RTA_DST | RTA_GATEWAY | RTA_NETMASK;
	msg.hdr.rtm_flags = RTF_UP | RTF_GATEWAY | RTF_STATIC;
	msg.hdr.rtm_pid = (int32_t)getpid();
	msg.hdr.rtm_seq = 1;

	msg.dst.sin_family = AF_INET;
	msg.dst.sin_len = sizeof(msg.dst);
	msg.dst.sin_addr.s_addr = 0;	/* 0.0.0.0 = default */

	msg.gw.sin_family = AF_INET;
	msg.gw.sin_len = sizeof(msg.gw);
	msg.gw.sin_addr = lease->router;

	msg.mask.sin_family = AF_INET;
	msg.mask.sin_len = sizeof(msg.mask);
	msg.mask.sin_addr.s_addr = 0;	/* /0 */

	sock = socket(AF_ROUTE, SOCK_RAW, 0);
	if (sock < 0) {
		xlog("socket(AF_ROUTE) failed: %s", strerror(errno));
		return (-1);
	}
	n = write(sock, &msg, sizeof(msg));
	if (n != (ssize_t)sizeof(msg)) {
		/* EEXIST is benign — the route is already there (a
		 * previous run, or a kernel default). Treat as success. */
		if (errno == EEXIST) {
			(void)close(sock);
			return (0);
		}
		xlog("write(PF_ROUTE, RTM_ADD default) failed: %s",
		    strerror(errno));
		(void)close(sock);
		return (-1);
	}
	(void)close(sock);
	return (0);
}

static int
write_resolv_conf(const struct dhcp_lease *lease)
{
	FILE *fp;

	if (lease->dns_count == 0)
		return (0);	/* nothing to write */

	/* Best-effort: write directly to /etc/resolv.conf. iter 4
	 * replaces this with a State:/Network/Global/DNS publish that
	 * a resolv.conf-rendering observer can consume. */
	fp = fopen("/etc/resolv.conf", "w");
	if (fp == NULL) {
		xlog("fopen(/etc/resolv.conf) failed: %s", strerror(errno));
		return (-1);
	}
	(void)fprintf(fp, "# Generated by ipconfigd (DHCPv4)\n");
	for (unsigned i = 0; i < lease->dns_count; i++) {
		char buf[INET_ADDRSTRLEN];

		if (inet_ntop(AF_INET, &lease->dns[i], buf, sizeof(buf))
		    != NULL)
			(void)fprintf(fp, "nameserver %s\n", buf);
	}
	(void)fclose(fp);
	return (0);
}

int
apply_lease(const char *ifname, const struct dhcp_lease *lease)
{
	int rc = 0;

	if (apply_address(ifname, lease) != 0)
		rc = -1;
	if (install_default_route(lease) != 0)
		rc = -1;
	/* DNS is best-effort; failure doesn't fail the apply. */
	(void)write_resolv_conf(lease);
	return (rc);
}
